### ISSUE TITLE
Update development docker-compose.yml to use a named volume for postgres

### ISSUE THREAD

**Issue by grahamhoyes** [ieeeuoft/hackathon-template#199]
Our current compose file has some issues:
- The `.postgres-data` volume doesn't work on windows
- It also sometimes doesn't work on mac
- When running multiple instances of the site (eg newhacks and the template), both database containers get the same name

Update the compose file to be something like:
```yaml
version: '3'

services:
    postgres:
        image: postgres:12.2
        container_name: hackathon_template_postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=hackathon_site
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - hackathon_template-postgres-data:/var/lib/postgresql/data

volumes:
    hackathon_template-postgres-data:
```

- The `container_name` can be updated in template instances to explicitly change the name for different projects
- The named volume works on all systems where a local mount doesn't, for some reason. Adding `hackathon_template` to the volume name allows us to set different volume names for template instances, so the databases don't conflict

It would also be nice to have a django container, so people don't have to install everything locally. Running the `yarn scss-watch` command would also be nice.
